services:
  db:
    image: mysql:8
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - db

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    env_file:
      - ./product-service/.env
    ports:
      - "5002:5000"
    depends_on:
      - db

  cart-service:
    build:
      context: .
      dockerfile: ./cart-service/Dockerfile
    container_name: cart-service
    env_file:
      - ./cart-service/.env
    ports:
      - "5003:5000"
    depends_on:
      - db
  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    container_name: order-service
    env_file:
      - ./order-service/.env
    ports:
      - "5004:5000"
    depends_on:
      - db

volumes:
  mysql-data:
